version: "3.8"
services:
  app:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - .:/app
  mongodb:
    image : mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ledn
    volumes:
    - /home/luke/data/mongodb:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped